import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import { DM_Sans} from "next/font/google";
//import { Geologica} from "next/font/google";
import "./globals.css";
import { TopNavBar } from "./components/TopNavBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const font = DM_Sans ({ subsets: ["latin"] });
//const font = Geologica ({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      //className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      // >
         className={`${font.className} antialiased`} suppressHydrationWarning={true}
      >
        <TopNavBar />
        {children}
      </body>
    </html>
  );
}
